[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root
childlogdir=/var/log/supervisor

[program:flask]
command=python3 /app/web-ui/app.py
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/flask.log
stderr_logfile=/var/log/supervisor/flask.log
environment=PYTHONUNBUFFERED="1"

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/null
stderr_logfile=/dev/null

[program:crond]
command=crond -f -l 8
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/crond.log
stderr_logfile=/var/log/supervisor/crond.log

[program:nginx-log-clean]
command=/bin/sh -c "sleep 5 && truncate -s 0 /var/log/nginx/error.log"
autostart=true
autorestart=false
startsecs=0
exitcodes=0
stdout_logfile=/dev/null
stderr_logfile=/dev/null
